<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>My Simple PHP Website</title>
    <link rel="stylesheet" href="style.css">
</head>
<body>
    <?php include 'header.php'; ?>

    <main>
        <h1>Welcome to My Website!</h1>
        <p>This is the homepage of my simple PHP website.</p>

        <?php
        // Example of dynamic content generated by PHP
        $currentTime = date("Y-m-d H:i:s");
        echo "<p>The current time is: " . $currentTime . "</p>";
        ?>
    </main>

    <?php include 'footer.php'; ?>
</body>
</html>
2. header.php:

PHP

<header>
    <div class="logo">My Website</div>
    <nav>
        <ul>
            <li><a href="index.php">Home</a></li>
            <li><a href="about.php">About</a></li>
            <li><a href="contact.php">Contact</a></li>
        </ul>
    </nav>
</header>